version: '3.8'
services:
  caddy:
    container_name: caddy
    image: caddy
    hostname: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /f/docker/media/caddy/etc:/etc/caddy
      - caddy_data:/data

  jackett:
    image: cr.hotio.dev/hotio/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
      - AUTO_UPDATE=true #optional
    volumes:
      - /f/docker/media/jackett:/config
      - /f/media/downloads:/downloads
    expose:
      - 9117
    restart: unless-stopped
  
  qbittorrent:
    image: cr.hotio.dev/hotio/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbit
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
      - WEBUI_PORT=8080
    volumes:
      - /f/docker/media/qbit:/config
      - /f/media/downloads:/downloads
    expose:
      - 8080
      - 6881
      - 6881/udp
    restart: unless-stopped

  bazarr:
    image: cr.hotio.dev/hotio/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
    volumes:
      - /f/docker/media/bazarr:/config
      - /f/media/movies:/movies #optional
      - /f/media/series:/tv #optional
    expose:
      - 6767

  radarr:
    image: cr.hotio.dev/hotio/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
    volumes:
      - /f/docker/media/radarr:/config
      - /f/media/movies:/movies #optional
      - /f/media/downloads:/downloads #optional
    expose:
      - 7878
    restart: unless-stopped

  sonarr:
    image: cr.hotio.dev/hotio/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
    volumes:
      - /f/docker/media/sonarr:/config
      - /f/media/series:/tv #optional
      - /f/media/downloads:/downloads #optional
    expose:
      - 8989
    restart: unless-stopped

  ombi:
    image: cr.hotio.dev/hotio/ombi:latest
    container_name: ombi
    hostname: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
    volumes:
      - /f/docker/media/ombi:/config
    expose:
      - 3579
    restart: unless-stopped

  jellyfin:
    image: cr.hotio.dev/hotio/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
    volumes:
      - /f/docker/media/jellyfin:/config
      - /f/media/series:/data/tvshows
      - /f/media/movies:/data/movies
    expose:
      - 8096
      - 8920 #optional
      - 7359/udp #optional
      - 1900/udp #optional
    restart: unless-stopped

  organizr:
      container_name: organizr
      hostname: organizr
      image: organizr/organizr:latest
      restart: unless-stopped
      expose:
          - 80
      volumes:
          - /f/docker/media/organize:/config
      environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/Ljubljana
  
    
volumes:
  caddy_data: {}
    
