version: '3.8'
services:
  jackett:
    image: cr.hotio.dev/hotio/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
      - AUTO_UPDATE=true #optional
    volumes:
      - ${CONFIG}/jackett:/config
      - ${MEDIA}/downloads:/downloads
    ports:
      - 10001:9117
    restart: unless-stopped
  
  qbittorrent:
    image: cr.hotio.dev/hotio/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbit
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG}/qbit:/config
      - ${MEDIA}/downloads:/downloads
    ports:
      - 10000:8080
    restart: unless-stopped

  bazarr:
    image: cr.hotio.dev/hotio/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
    volumes:
      - ${CONFIG}/bazarr:/config
      - ${MEDIA}/movies:/movies #optional
      - ${MEDIA}/series:/tv #optional
    ports:
      - 10005:6767

  radarr:
    image: cr.hotio.dev/hotio/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
    volumes:
      - ${CONFIG}/radarr:/config
      - ${MEDIA}/movies:/movies #optional
      - ${MEDIA}/downloads:/downloads #optional
    ports:
      - 10003:7878
    restart: unless-stopped

  sonarr:
    image: cr.hotio.dev/hotio/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${MEDIA}/series:/tv #optional
      - ${MEDIA}/downloads:/downloads #optional
    ports:
      - 10004:8989
    restart: unless-stopped

  ombi:
    image: cr.hotio.dev/hotio/ombi:latest
    container_name: ombi
    hostname: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
    volumes:
      - ${CONFIG}/ombi:/config
    ports:
      - 11000:5000
    restart: unless-stopped

  jellyfin:
    image: cr.hotio.dev/hotio/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
    volumes:
      - ${CONFIG}/jellyfin:/config
      - ${MEDIA}/series:/data/tvshows
      - ${MEDIA}/movies:/data/movies
    ports:
      - 11001:8096
      - 1900:1900/udp
      - 7359:7359/udp
    restart: unless-stopped
