version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - {DATA}/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8010:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - {DATA}/data/data:/usr/src/paperless/data
      - {DATA}/data/media:/usr/src/paperless/media
      - {DATA}/data/export:/usr/src/paperless/export
      - {DATA}/data/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db

      USERMAP_UID: 1000
      USERMAP_GID: 1000

      PAPERLESS_OCR_LANGUAGES: slv bos ita hrv

      PAPERLESS_TIME_ZONE: Europe/Ljubljana

      PAPERLESS_OCR_LANGUAGE: slv
      PAPERLESS_CONSUMER_POLLING: 60
      PAPERLESS_SECRET_KEY: {SECRET_KEY}
